### ISSUE TITLE
GUI for Annotation

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Computational-Social-Research#6]
Create a easily usable and user friendly GUI for text annotation.

A swipe app. The app shows a text. 

- If you swipe left, the text is annotated with class label X.
- If you swipe right, this means class label Y.
- If you swipe up or down, you can cycle for more labels: X and Y become A and B.
- You can tap individual words in the text for fine-grained annotations.
- Add icon buttons near the fine-grained labels.
- Next, prev, undo, redo
- Excels

Enhancement - If the app learns and predics as and while user annotate.

**Comment by dhirensr** [comment]
@tapaswenipathak : GUI would be a mobile app or any GUI?

**Comment by tapaswenipathak** [comment]
Mobile app.

**Comment by dhirensr** [comment]
@tapaswenipathak : not assigning myself here because i am not good at mobile apps

**Comment by bhaumikmistry** [comment]
Add an example for each case. @tapaswenipathak
