### ISSUE TITLE
GUI for decision Trees

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Computational-Social-Research#7]
For generating quick logic flow for decision-making. 

The app would have a "node panel", with a unique id and a text field. The user could add text, a formula, source code.

- A node has 1-9 variables with default values, that the user can define (e.g., name = Alice). The text field can refer these variables (e.g., "Hello, <name>!").
- A node has 1-9 effects, that set state variable (e.g., X is/has/likes/hates/knows Y).
- A node has a branch condition. This condition can be a question that user can define (e.g., "Are you happy or sad, <name>?") and/or state variable filters (X must know Y).
- For each of these node id’s, the node’s variable defaults can be overridden.

**Comment by bhaumikmistry** [comment]
A drawing would be more helpful. @tapaswenipathak
