### ISSUE TITLE
Please explore http://www.internationalgenome.org/data-portal/sample

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Computational-Social-Research#9]
<img width="1027" alt="Screen Shot 2019-07-10 at 1 03 14 AM" src="https://user-images.githubusercontent.com/4143778/60917374-6db37f00-a2ae-11e9-9af7-7d8d8dbee790.png">

**Comment by tapaswenipathak** [comment]
@sujaykumarreddy Doc?

**Comment by sujay0399** [comment]
@tapaswenipathak I'm working on it.

**Comment by tapaswenipathak** [comment]
https://paper.dropbox.com/doc/genomics-sample-summary--Ag41LD2etpbrvh8IjzxioGlAAQ-6hlM3Fi5rIGWHlrUFvBjd
